parameters:
    codingfogey_font_awesome.twig.extension.class: Codingfogey\Bundle\FontAwesomeBundle\Twig\FontAwesomeExtension

services:
    codingfogey_font_awesome.twig.extension:
        class: %codingfogey_font_awesome.twig.extension.class%
        tags:
            - { name: twig.extension }
